baseURL = "/"
languageCode = "ar"
title = "TechTouch Channels"

[menu]
  [[menu.main]]
    name = "الرئيسية"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "قنواتي"
    url = "/channels/"
    weight = 20
  [[menu.main]]
    name = "المنشورات"
    url = "/posts/"
    weight = 30
