baseURL = "/"
languageCode = "ar-SA"
title = "TechTouch Channels"
theme = "ananke"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "المنشورات"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "channels"
    name = "القنوات"
    url = "/channels/"
    weight = 2
