# Enhanced Netlify configuration for TechTouch

# Build settings
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_FLAGS = "--no-audit --no-fund"
    NODE_ENV = "production"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googleapis.com *.googletagmanager.com;
      style-src 'self' 'unsafe-inline' *.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' data: *.googleapis.com;
      connect-src 'self' *.googleapis.com *.google.com;
      media-src 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
    """

# CORS headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Cache CSS and JS
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Functions directory
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@google/genai"]

# Development settings
[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173
  autoLaunch = true

# Branch deploy settings
[context.branch-deploy]
  command = "npm run build"
  [context.branch-deploy.environment]
    NODE_ENV = "development"
    API_RATE_LIMIT = "20"

[context.deploy-preview]
  command = "npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    API_RATE_LIMIT = "50"

[context.production.environment]
  NODE_ENV = "production"
  API_RATE_LIMIT = "10"
