# هذا هو ملف الإعدادات الخاص بـ Netlify
# يحدد كيفية بناء ونشر الموقع

[build]
  # الأمر الذي يتم تشغيله لبناء الموقع.
  # لقد أضفنا هذا الأمر في ملف package.json لحل مشكلة النشر.
  command = "npm run build"

  # المجلد الذي يحتوي على ملفات الموقع الجاهزة للنشر.
  # "." تعني المجلد الرئيسي للمشروع، وهذا صحيح لأن ملف index.html موجود هناك.
  publish = "."

[functions]
  # المجلد الذي يحتوي على الوظائف الخلفية (Serverless Functions).
  # وظيفة البحث بالذكاء الاصطناعي موجودة في هذا المسار.
  directory = "netlify/functions"
