# هذا الملف يقوم بإعادة توجيه جميع الطلبات إلى index.html
# وهو أمر ضروري لتطبيقات الصفحة الواحدة (SPA) مثل React
# لتعمل بشكل صحيح على Netlify وتجنب أخطاء "Page Not Found".
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
