# إعدادات البناء
[build]
  # هذا الأمر يتم تشغيله عند نشر الموقع.
  command = "npm run build"
  
  # هذا هو المجلد الذي يحتوي على ملفات الموقع الجاهزة للنشر.
  # بما أن ملف index.html موجود في المجلد الرئيسي، تم تعيينه إلى "."
  publish = "."
  
  # المجلد الذي سيجد فيه Netlify الدوال البرمجية (serverless functions).
  functions = "netlify/functions"

# قاعدة إعادة توجيه للتطبيقات أحادية الصفحة (SPA)
# هذا يضمن أن يتم التعامل مع جميع الطلبات من خلال ملف index.html.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
