# ==============================================================================
# اعدادات البناء (Build Settings)
# ==============================================================================
# هذا القسم يخبر Netlify بكيفية بناء موقعك.
[build]
  # أمر البناء الذي سيتم تنفيذه.
  # بناءً على ملف package.json، هذا هو الأمر الصحيح.
  command = "vite build"

  # المجلد الذي يحتوي على الملفات النهائية بعد البناء.
  # المجلد الافتراضي لمخرجات Vite هو "dist".
  publish = "dist"

  # المجلد الذي يحتوي على وظائف الخادم (Netlify Functions).
  functions = "netlify/functions"

# ==============================================================================
# إعدادات إعادة التوجيه (Redirects)
# ==============================================================================
# هذا القسم ضروري لتطبيقات الصفحة الواحدة (SPAs) مثل React.
# يضمن أن جميع الطلبات تذهب إلى ملف index.html الرئيسي،
# مما يسمح لـ React بمعالجة التوجيه من جانب العميل.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ==============================================================================
# إعدادات وظائف الخادم (Functions Settings)
# ==============================================================================
# هذا القسم يسمح بتخصيص سلوك وظائف الخادم الفردية.

# إعدادات وظيفة البحث بالذكاء الاصطناعي (ai-search).
[functions."ai-search"]
  # زيادة مهلة التنفيذ إلى 25 ثانية.
  # القيمة الافتراضية هي 10 ثواني، وهو وقت قد لا يكون كافيًا
  # لاستجابات الذكاء الاصطناعي، مما قد يسبب أخطاء "timeout".
  timeout = 25

# إعدادات وظيفة أخبار الذكاء الاصطناعي (ai-news).
[functions."ai-news"]
  # زيادة مهلة التنفيذ إلى 25 ثانية لنفس السبب أعلاه.
  timeout = 25
