# لإعدادات النشر على Netlify.
# أعد تسمية هذا الملف إلى netlify.toml لتفعيله.

# مثال لتوجيه تطبيق صفحة واحدة (SPA) مثل React
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
