# Netlify configuration file

# Build settings: Specifies the command to build the site and the directory where the built files are located.
[build]
  command = "npm run build"
  publish = "dist"

# Redirects and rewrites: This rule is essential for Single Page Applications (SPAs).
# It ensures that any request that doesn't match a static file is redirected to index.html,
# allowing the client-side router to handle the path.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Serverless Functions configuration
[functions]
  # Increase the timeout for the specified function.
  # The default timeout is 10 seconds. We're increasing it to 25 seconds
  # to prevent gateway timeout errors when the Gemini API takes longer to respond.
  [functions."ai-news"]
    timeout = 25
