# إعدادات البناء لتطبيق صفحة واحدة يعتمد على Vite
[build]
  command = "npm run build"
  publish = "dist"

# قاعدة إعادة التوجيه لتطبيقات الصفحة الواحدة للتعامل مع التوجيه من جانب العميل
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# إعدادات الدوال التي لا تحتاج إلى خادم (Serverless Functions)
[functions]
  # زيادة مهلة التنفيذ لجميع الدوال إلى 25 ثانية (الافتراضي هو 10 ثوانٍ)
  # هذا يمنع أخطاء البوابة (gateway errors) للمهام التي تستغرق وقتًا أطول مثل توليد استجابات الذكاء الاصطناعي.
  timeout = 25
