# Netlify configuration file

# Build settings
[build]
  # Command to build the site
  command = "npm run build"
  # Directory to publish
  publish = "dist"
  # Directory with serverless functions
  functions = "netlify/functions"

# Local development settings for 'netlify dev'
[dev]
  # Command to start the development server
  command = "npm run dev"
  # Port for the development server
  targetPort = 5173
  # Port for the Netlify Dev server
  port = 8888
  # The directory to publish from
  publish = "dist"

# Redirect rule for Single Page Applications (SPA)
# This ensures that all routes are handled by your React app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
