# إعدادات البناء الأساسية
[build]
  # الأمر الذي يتم تشغيله لبناء الموقع. سيستخدم الأمر "npm run build" الموجود في ملف package.json.
  command = "npm run build"
  
  # هذا هو الجزء الأهم. يخبر Netlify أن المجلد الذي يجب نشره هو المجلد الرئيسي (".")
  # هذا يحل مشكلة "Deploy directory 'dist' does not exist".
  publish = "."
  
  # المجلد الذي يحتوي على دوال serverless الخاصة بك (مثل ai-search.ts).
  functions = "netlify/functions"

# قاعدة إعادة توجيه للتعامل مع التطبيقات أحادية الصفحة (SPA) مثل React
# هذا يضمن أن جميع المسارات يتم توجيهها إلى ملف index.html الرئيسي.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
