# إعدادات النشر الأساسية لموقعك
[build]
  # الأمر الذي يتم تنفيذه لبناء الموقع
  command = "npm run build"
  
  # المجلد الذي يحتوي على ملفات الموقع النهائية بعد البناء
  # بالنسبة لمشاريع Vite، يكون هذا المجلد هو "dist" عادةً
  publish = "dist"
  
  # المجلد الذي يحتوي على وظائف Netlify (serverless functions)
  functions = "netlify/functions"

# قاعدة إعادة توجيه لمعالجة التطبيقات أحادية الصفحة (SPA) مثل React
# هذا يضمن أن جميع الطلبات تذهب إلى index.html ليعمل التوجيه من جانب العميل
# بشكل صحيح عند تحديث الصفحة أو الدخول إلى رابط مباشر
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
