
import React, { useState } from 'react';

interface AiImagePageProps {
  onNavigateHome: () => void;
}

const AiImagePage: React.FC<AiImagePageProps> = ({ onNavigateHome }) => {
  const [prompt, setPrompt] = useState('');
  const [generatedImage, setGeneratedImage] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerate = async () => {
    if (!prompt.trim()) {
      setError('الرجاء إدخال وصف للصورة.');
      return;
    }

    setIsLoading(true);
    setError('');
    setGeneratedImage(null);

    try {
      const response = await fetch('/.netlify/functions/ai-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt }),
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({ error: 'فشل في تحليل استجابة الخطأ من الخادم.' }));
        throw new Error(errorData.error || `فشل في توليد الصورة. (Status: ${response.status})`);
      }

      const { image: base64Image } = await response.json();
      if (!base64Image) {
        throw new Error('لم يتم إرجاع أي صورة من الخادم.');
      }
      setGeneratedImage(`data:image/png;base64,${base64Image}`);
    } catch (e: any) {
      console.error(e);
      setError(e.message || 'حدث خطأ غير متوقع.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey && !isLoading) {
      e.preventDefault();
      handleGenerate();
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-slate-800 to-gray-900 text-white font-sans">
      <main className="container mx-auto px-4 py-8">
        <div className="mb-8">
          <button onClick={onNavigateHome} className="flex items-center gap-2 text-gray-300 hover:text-teal-300 transition-colors duration-300 text-lg" aria-label="العودة للصفحة الرئيسية">
            <i className="fas fa-arrow-left"></i><span>العودة</span>
          </button>
        </div>

        <div className="w-full max-w-3xl mx-auto">
          <h1 className="text-3xl md:text-4xl font-bold mb-2 text-center text-transparent bg-clip-text bg-gradient-to-r from-teal-300 to-sky-500">
            توليد الصور بالذكاء الاصطناعي
          </h1>
          <p className="text-center text-gray-400 mb-8">
            أطلق العنان لإبداعك. اكتب وصفًا وسيقوم الذكاء الاصطناعي بتحويله إلى صورة.
          </p>

          <div className="bg-gray-800/50 p-6 rounded-xl shadow-lg border border-gray-700">
            <div className="space-y-4">
              <textarea
                placeholder="مثال: قطة رائد فضاء ترتدي خوذة زجاجية، بأسلوب فن رقمي مفصل..."
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                onKeyPress={handleKeyPress}
                className="w-full p-4 bg-gray-900 border-2 border-gray-600 rounded-lg text-white placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-teal-500 transition-all duration-300 resize-none h-24"
                aria-label="Image generation prompt"
                disabled={isLoading}
                autoFocus
              />
              <button onClick={handleGenerate} disabled={isLoading} className="w-full bg-teal-600 text-white font-bold py-3 px-8 rounded-full hover:bg-teal-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-900 focus:ring-teal-500 transition-all duration-300 disabled:bg-gray-600 disabled:cursor-not-allowed flex items-center justify-center gap-2 text-lg">
                {isLoading ? (<><i className="fas fa-spinner fa-spin"></i><span>جاري التوليد...</span></>) : (<><i className="fas fa-magic"></i><span>توليد الصورة</span></>)}
              </button>
            </div>
          </div>

          {error && <p className="text-sky-400 mt-4 text-center bg-gray-800 p-3 rounded-lg">{error}</p>}
          
          <div className="mt-8">
            {isLoading && (
              <div className="aspect-square w-full bg-gray-800/50 rounded-lg flex items-center justify-center border-2 border-dashed border-gray-600 animate-pulse">
                <div className="text-center text-gray-500">
                  <i className="fas fa-image text-5xl mb-4"></i>
                  <p>يتم الآن إنشاء تحفتك الفنية...</p>
                </div>
              </div>
            )}
            {generatedImage && (
              <div className="aspect-square w-full rounded-lg overflow-hidden shadow-2xl border-2 border-teal-500/50">
                <img src={generatedImage} alt="Generated by AI" className="w-full h-full object-contain bg-gray-900" />
              </div>
            )}
            {!isLoading && !generatedImage && (
              <div className="aspect-square w-full bg-gray-800/50 rounded-lg flex items-center justify-center border-2 border-dashed border-gray-600">
                <div className="text-center text-gray-500">
                  <i className="fas fa-palette text-5xl mb-4"></i>
                  <p>ستظهر صورتك المولدة هنا</p>
                </div>
              </div>
            )}
          </div>
        </div>
      </main>
    </div>
  );
};

export default AiImagePage;
